export { default as BasicInput } from './InputType1'
export { default as ConsultInput } from './InputConsult'
export { default as BasicSelect } from './SelectComponentType1'
export { default as InputDate } from './InputDate'
export { default as CheckInput } from './CheckInput'